"""A study: the runs behind a set of findings, kept in the repo, and the tables made from them.

A study is a directory with a `findings.toml`. The manifest names the study's runs, each with a
role, and the tables to make from them:

    [study]
    name = "dsh-pilot"
    collection = "dsh-archive"            # where `bundle` finds runs given by id
    models_file = "../../../pilots/models.toml"

    [[runs]]
    id = "01M46QWP6CTEM5DN807VS7GQMW"
    role = "versions"
    label = "v1"                          # names the run's component version on a version board

    [[tables]]
    name = "pilot"
    kind = "leaderboard"                  # leaderboard | version-board | report
    roles = ["versions"]

`bundle` copies each run's `run.json` and `results.jsonl` into `runs/<id>/`, and never a transcript.
`tables` makes every table from those copies alone, so a clone regenerates every number:
`tables/<name>.md` as the pooled output gives it, `tables/<name>.slim.md` sized for a slide, and
one long-format `findings.csv`. Paths in the manifest are relative to the study directory.
"""

from __future__ import annotations

import csv
import dataclasses
import filecmp
import io
import json
import re
import shutil
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import catalogue as catalogue_mod
from . import compare, leaderboard, names, present
from . import report as report_mod
from . import version_board as board_mod
from .catalogue import Catalogue
from .compare import LoadedRun, Rate, wilson
from .errors import WikiskillError
from .runner.base import INJECTED

MANIFEST = "findings.toml"
KINDS = ("leaderboard", "version-board", "report")
RUN_FILES = ("run.json", "results.jsonl")
#: The first line of every generated file, which `--check` and readers both go by.
GENERATED = "<!-- generated by `wikiskill findings tables`; do not edit -->"
#: A slide-sized table has no more columns than this.
SLIM_COLUMNS = 6
CSV_COLUMNS = (
    "table",
    "kind",
    "entrant",
    "model",
    "family",
    "size_b",
    "condition",
    "version",
    "task",
    "passed",
    "total",
    "rate",
    "low",
    "high",
    "lift",
    "direction",
    "outcomes",
    "median_s",
    "median_tokens_in",
    "median_tokens_out",
    "runs",
)


class FindingsError(WikiskillError):
    """A study that cannot be read, bundled or tabled as it stands."""


@dataclass(frozen=True)
class StudyRun:
    id: str
    role: str
    label: str | None = None
    path: str | None = None


@dataclass(frozen=True)
class Table:
    name: str
    kind: str
    roles: tuple[str, ...]
    component: str | None = None
    baseline: str | None = None
    critical: str | None = None
    condition: str | None = None


@dataclass
class Study:
    root: Path
    name: str
    collection: str | None
    models_file: str | None
    runs: list[StudyRun] = field(default_factory=list)
    tables: list[Table] = field(default_factory=list)

    def bundled(self, run: StudyRun) -> Path:
        return self.root / "runs" / run.id

    def runs_for(self, table: Table) -> list[StudyRun]:
        return [run for run in self.runs if run.role in table.roles]

    def resolve(self, relative: str) -> Path:
        return (self.root / relative).resolve()


# --------------------------------------------------------------------------- the manifest


def load(root: str | Path) -> Study:
    root = Path(root)
    path = root / MANIFEST
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise FindingsError(f"no study at {root}: cannot read {MANIFEST} ({exc})") from exc
    except tomllib.TOMLDecodeError as exc:
        raise FindingsError(f"{path} is not valid TOML: {exc}") from exc
    head = document.get("study") or {}
    if not isinstance(head, dict) or not isinstance(head.get("name"), str):
        raise FindingsError(f"{path} needs a `[study]` table with a `name`")
    study = Study(
        root=root,
        name=head["name"],
        collection=head.get("collection"),
        models_file=head.get("models_file"),
    )
    problems: list[str] = []
    seen: set[str] = set()
    for number, raw in enumerate(document.get("runs") or [], start=1):
        run = _run(raw, number, problems)
        if run is None:
            continue
        if run.id in seen:
            problems.append(f"run {run.id} is named twice")
        seen.add(run.id)
        study.runs.append(run)
    roles = {run.role for run in study.runs}
    names: set[str] = set()
    for number, raw in enumerate(document.get("tables") or [], start=1):
        table = _table(raw, number, roles, problems)
        if table is None:
            continue
        if table.name in names:
            problems.append(f"table {table.name!r} is named twice")
        names.add(table.name)
        study.tables.append(table)
    if problems:
        raise FindingsError(f"{path}: " + "; ".join(problems))
    return study


def _run(raw: Any, number: int, problems: list[str]) -> StudyRun | None:
    if not isinstance(raw, dict) or not isinstance(raw.get("id"), str) or not raw["id"]:
        problems.append(f"run {number} needs an `id`")
        return None
    if not isinstance(raw.get("role"), str) or not raw["role"]:
        problems.append(f"run {raw['id']} needs a `role`")
        return None
    extra = set(raw) - {"id", "role", "label", "path"}
    if extra:
        problems.append(f"run {raw['id']} has unknown keys: {', '.join(sorted(extra))}")
    return StudyRun(id=raw["id"], role=raw["role"], label=raw.get("label"), path=raw.get("path"))


def _table(raw: Any, number: int, roles: set[str], problems: list[str]) -> Table | None:
    if not isinstance(raw, dict) or not isinstance(raw.get("name"), str):
        problems.append(f"table {number} needs a `name`")
        return None
    name = raw["name"]
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name):
        problems.append(f"table {name!r}: a name is lowercase letters, digits and dashes")
    kind = raw.get("kind")
    if kind not in KINDS:
        problems.append(f"table {name!r}: `kind` must be one of {', '.join(KINDS)}, not {kind!r}")
    wanted = raw.get("roles")
    if not isinstance(wanted, list) or not wanted:
        problems.append(f"table {name!r} needs `roles`, a list of run roles")
        wanted = []
    for role in wanted:
        if role not in roles:
            problems.append(f"table {name!r} draws on role {role!r}, which no run has")
    if kind == "version-board" and not raw.get("component"):
        problems.append(f"table {name!r}: a version board needs a `component`")
    extra = set(raw) - {"name", "kind", "roles", "component", "baseline", "critical", "condition"}
    if extra:
        problems.append(f"table {name!r} has unknown keys: {', '.join(sorted(extra))}")
    return Table(
        name=name,
        kind=str(kind),
        roles=tuple(str(role) for role in wanted),
        component=raw.get("component"),
        baseline=raw.get("baseline"),
        critical=raw.get("critical"),
        condition=raw.get("condition"),
    )


def add(root: str | Path, run_id: str, role: str, label: str | None = None) -> None:
    """Append one run to a study's manifest. A run already there is refused."""
    study = load(root)
    if any(run.id == run_id for run in study.runs):
        raise FindingsError(f"run {run_id} is already in {study.root / MANIFEST}")
    for name, value in (("id", run_id), ("role", role), ("label", label or "")):
        if '"' in value or "\\" in value or "\n" in value:
            raise FindingsError(f"the run's {name} cannot hold quotes, backslashes or newlines")
    block = f'\n[[runs]]\nid = "{run_id}"\nrole = "{role}"\n'
    if label:
        block += f'label = "{label}"\n'
    path = study.root / MANIFEST
    text = path.read_text(encoding="utf-8")
    path.write_text(text.rstrip("\n") + "\n" + block, encoding="utf-8")
    load(root)


# --------------------------------------------------------------------------- bundling


@dataclass
class BundleResult:
    copied: list[str] = field(default_factory=list)
    kept: list[str] = field(default_factory=list)
    changed: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)


def bundle(study: Study) -> BundleResult:
    """Copy each run's `run.json` and `results.jsonl` into the study; never overwrite one."""
    found = BundleResult()
    for run in study.runs:
        try:
            source = compare.load_run(study.collection or "", run.path or run.id).root
        except compare.CompareError:
            source = None
        target = study.bundled(run)
        if target.is_dir():
            if source is None or all(
                filecmp.cmp(source / name, target / name, shallow=False)
                for name in RUN_FILES
                if (source / name).is_file()
            ):
                found.kept.append(run.id)
            else:
                found.changed.append(run.id)
            continue
        if source is None:
            found.missing.append(run.id)
            continue
        target.mkdir(parents=True)
        for name in RUN_FILES:
            if (source / name).is_file():
                shutil.copyfile(source / name, target / name)
        found.copied.append(run.id)
    return found


# --------------------------------------------------------------------------- tables


@dataclass
class Rendered:
    """Every generated file, by path relative to the study, with its content."""

    files: dict[str, str] = field(default_factory=dict)
    rows: list[dict[str, Any]] = field(default_factory=list)


def render(study: Study) -> Rendered:
    """Every declared table, from the bundled runs alone."""
    catalogue = _catalogue(study)
    out = Rendered()
    for table in study.tables:
        runs = _loaded(study, table)
        if table.kind == "leaderboard":
            full, slim, rows = _leaderboard(runs, catalogue)
        elif table.kind == "version-board":
            full, slim, rows = _version_board(study, table, runs, catalogue)
        else:
            full, slim, rows = _report(runs, catalogue)
        out.files[f"tables/{table.name}.md"] = _generated(full)
        # One table per slim file: pandoc moves a second table on a slide to a slide of its own.
        for part, text in slim.items():
            suffix = f".{part}" if part else ""
            out.files[f"tables/{table.name}{suffix}.slim.md"] = _generated(text)
        out.rows += [{"table": table.name, "kind": table.kind, **row} for row in rows]
    out.files["findings.csv"] = _csv(out.rows)
    return out


def write(study: Study, rendered: Rendered) -> list[Path]:
    written = []
    for relative, text in rendered.files.items():
        path = study.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def stale(study: Study, rendered: Rendered) -> list[str]:
    """Generated files that differ from what the bundle now gives, or are missing."""
    found = []
    for relative, text in rendered.files.items():
        path = study.root / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            found.append(relative)
    return found


def _catalogue(study: Study) -> Catalogue | None:
    if not study.models_file:
        return None
    try:
        loaded = catalogue_mod.load(study.resolve(study.models_file))
    except catalogue_mod.CatalogueError as exc:
        raise FindingsError(str(exc)) from exc
    # Named as the manifest names it, so the output reads the same on every machine.
    return dataclasses.replace(loaded, source=study.models_file)


def _loaded(study: Study, table: Table) -> list[LoadedRun]:
    runs = []
    for run in study.runs_for(table):
        path = study.bundled(run)
        if not (path / "run.json").is_file():
            raise FindingsError(
                f"run {run.id} is not bundled; run `wikiskill findings bundle {study.root}` first"
            )
        loaded = compare.load_run("", path)
        runs.append(dataclasses.replace(loaded, root=Path("runs") / run.id))
    if not runs:
        raise FindingsError(f"table {table.name!r} has no runs")
    return runs


def _generated(markdown: str) -> str:
    return f"{GENERATED}\n\n{markdown.strip()}\n"


def _demoted(markdown: str, levels: int = 2) -> str:
    """Headings moved down, so a fragment sits under the document's own sections."""
    return re.sub(
        r"^(#{1,6}) ", lambda m: "#" * min(6, len(m[1]) + levels) + " ", markdown, flags=re.M
    )


def _leaderboard(
    runs: list[LoadedRun], catalogue: Catalogue | None
) -> tuple[str, dict[str, str], list[dict[str, Any]]]:
    try:
        board = leaderboard.pool(runs, catalogue)
    except (leaderboard.LeaderboardError, compare.CompareError) as exc:
        raise FindingsError(str(exc)) from exc
    full = _demoted(leaderboard.render(board))
    data = board.as_dict()["ranking"]
    order = {model: index for index, model in enumerate(board.models_in_order)}
    slim_rows = sorted(
        (
            (order.get(entry["model"], len(order)), condition, entry)
            for condition, entries in data.items()
            for entry in entries
        ),
        key=lambda item: (item[0], item[1]),
    )
    slim = present.table(
        ["model", "family", "condition", "passed (95% CI)", "not run", "median s"],
        [
            [
                names.model_id(entry["model"]),
                entry.get("family") or present.MISSING,
                condition,
                present.rate(entry["passed"], entry["total"]),
                entry["not_run"],
                present.seconds(entry.get("median_duration_ms")),
            ]
            for _, condition, entry in slim_rows
        ],
    )
    rows = [_cell_row(board, cell, "") for cell in board.cells.values()]
    rows += [_cell_row(board, cell, task) for (task, _, _), cell in board.task_cells.items()]
    return full, {"": "\n".join(slim)}, rows


def _cell_row(board: leaderboard.Leaderboard, cell: leaderboard.Cell, task: str) -> dict[str, Any]:
    described = board.described(cell)
    info = cell.as_dict()
    return {
        "entrant": cell.model,
        "model": cell.base or cell.model,
        "family": described.get("family"),
        "size_b": described.get("size_b"),
        "condition": cell.condition,
        "version": "",
        "task": task,
        **_rate_columns(cell.rate),
        "outcomes": json.dumps(info["outcomes"], sort_keys=True),
        "median_s": _seconds(info["median_duration_ms"]),
        "median_tokens_in": info["median_tokens"]["input"],
        "median_tokens_out": info["median_tokens"]["output"],
        "runs": len(cell.runs),
    }


def _version_board(
    study: Study, table: Table, runs: list[LoadedRun], catalogue: Catalogue | None
) -> tuple[str, dict[str, str], list[dict[str, Any]]]:
    component = str(table.component)
    labels = {}
    for run, loaded in zip(study.runs_for(table), runs, strict=True):
        version = loaded.hashes().get(component)
        if run.label and version:
            labels[version] = run.label
    baseline = None
    if table.baseline:
        baseline = next((v for v, label in labels.items() if label == table.baseline), None)
        if baseline is None:
            raise FindingsError(
                f"table {table.name!r}: no run is labelled {table.baseline!r} for {component}"
            )
    critical = None
    if table.critical:
        try:
            critical = board_mod.load_critical(study.resolve(table.critical))
        except board_mod.BoardError as exc:
            raise FindingsError(str(exc)) from exc
        critical = dataclasses.replace(critical, source=table.critical)
    try:
        board = board_mod.pool(
            runs,
            component,
            condition=table.condition or INJECTED,
            baseline=baseline,
            labels=labels,
            critical=critical,
            catalogue=catalogue,
        )
    except (WikiskillError, ValueError) as exc:
        raise FindingsError(f"table {table.name!r}: {exc}") from exc
    full = _demoted(board_mod.render(board))
    data = board.as_dict()
    per_model = present.table(
        ["model", "family", "OFF", "best version", "passed (95% CI)", "lift"],
        [_best_row(board, model) for model in board.models],
    )
    overall = present.table(
        ["version", "mean", "won", "lost", "regressions", "disqualified"],
        [
            [
                f"`{row['label']}`",
                present.pct(row["mean"]),
                row["won"],
                row["lost"],
                ", ".join(row["regressions"]) or present.MISSING,
                "yes" if row["disqualified"] else present.MISSING,
            ]
            for row in data["overall"]
        ],
    )
    slim = {"": "\n".join(per_model), "overall": "\n".join(overall)}
    rows = []
    for model in board.models:
        described = board.described(model)
        base = {
            "entrant": model,
            "model": board.base.get(model, model),
            "family": described.get("family"),
            "size_b": described.get("size_b"),
        }
        control = board.control.get(model)
        if control is not None:
            rows.append(
                {**base, "condition": "off", "version": "", "task": "", **_rate_columns(control)}
            )
        for entry in board.entries(model):
            rows.append(
                {
                    **base,
                    "condition": board.condition,
                    "version": board.label(entry.version),
                    "task": "",
                    **_rate_columns(entry.rate),
                    "lift": entry.lift,
                    "direction": entry.direction,
                }
            )
        for (cell_model, version, task), rate in sorted(board.matrix.items()):
            if cell_model == model:
                rows.append(
                    {
                        **base,
                        "condition": board.condition,
                        "version": board.label(version),
                        "task": task,
                        **_rate_columns(rate),
                    }
                )
    return full, slim, rows


def _best_row(board: board_mod.VersionBoard, model: str) -> list[Any]:
    best = board.best(model)
    control = board.control.get(model)
    return [
        names.model_id(model),
        board.described(model).get("family") or present.MISSING,
        present.of(control),
        f"`{board.label(best.version)}`" if best else present.MISSING,
        present.of(best.rate) if best else present.MISSING,
        present.pct(best.lift, signed=True) if best else present.MISSING,
    ]


def _report(
    runs: list[LoadedRun], catalogue: Catalogue | None
) -> tuple[str, dict[str, str], list[dict[str, Any]]]:
    full, slim_rows, rows = [], [], []
    for run in runs:
        built = report_mod.build_report(list(run.results), run.manifest, catalogue)
        full.append(f"## Run `{run.run_id}`\n\n" + _demoted(report_mod.render_markdown(built)))
        for row in built["rows"]:
            rows.append(
                {
                    "entrant": row["model"],
                    "model": row["model"],
                    "family": catalogue.family(row["model"]) if catalogue else None,
                    "size_b": _size(catalogue, row["model"]),
                    "condition": row["condition"],
                    "version": "",
                    "task": row["task_id"],
                    "rate": row.get("pass_rate"),
                    "outcomes": json.dumps(row.get("outcomes") or {}, sort_keys=True),
                    "runs": 1,
                }
            )
            rubric = row.get("rubric") or {}
            for dimension, counts in (rubric.get("dimensions") or {}).items():
                others = (rubric.get("others_majority") or {}).get(dimension)
                slim_rows.append(
                    [
                        row["task_id"],
                        names.model_id(row["model"]),
                        row["condition"],
                        dimension,
                        _levels(counts),
                        _levels(others) if others else present.MISSING,
                    ]
                )
    slim = present.table(
        ["task", "model", "condition", "dimension", "levels", "without same family"], slim_rows
    )
    text = "\n".join(slim) if slim_rows else "No rubric was judged."
    return "\n\n".join(full), {"": text}, rows


def _levels(counts: dict[str, int]) -> str:
    return ", ".join(f"{level} x{count}" for level, count in sorted(counts.items()))


def _size(catalogue: Catalogue | None, model: str) -> float | None:
    info = catalogue.get(model) if catalogue else None
    return info.size_b if info else None


def _rate_columns(rate: Rate) -> dict[str, Any]:
    low, high = wilson(rate.passed, rate.total) or (None, None)
    return {
        "passed": rate.passed,
        "total": rate.total,
        "rate": rate.rate,
        "low": low,
        "high": high,
    }


def _seconds(ms: float | None) -> float | None:
    return None if ms is None else ms / 1000


def _csv(rows: list[dict[str, Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=CSV_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({column: _cell(row.get(column)) for column in CSV_COLUMNS})
    return buffer.getvalue()


def _cell(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.6g}"
    return value
